### ISSUE TITLE
FDATE - overlooked or deprecated?

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [NOAA-EMC/global-workflow#1005]
**Expected behavior**
All variables are filled out in `config.base`

**Current behavior**
After running the refactored setup scripts, when looking at the `config.base` file, there is a line:
`export FDATE=@FDATE@ `

Is this intentional? An oversight? What exactly is `$FDATE`? I see it being used here in `config.anal`:
https://github.com/NOAA-EMC/global-workflow/blob/392ca6fc71c390a75cf0c4d621daa491c721e08a/parm/config/config.anal#L15

When running a cycled experiment with older (pre GFSv16) ICs, the `gdasanal` job fails because it is trying to untar netCDF diagnostic files, but they are archived as binary diagnostic files. Removing the `FDATE` part of the above `if` causes the job to complete. 

My question is: is `$FDATE` used anywhere else? If not, can we modify `config.anal` to not key off of it?

**Machines affected**
all?

**To Reproduce**
Setup a cycled experiment and look at `config.base`.

**Comment by WalterKolczynski-NOAA** [comment]
I suspect silently deprecated is the right answer. Those are the only two mentions I see anywhere in the code base. I don't know that having an `FDATE` is necessary. @aerorahul?

**Comment by RussTreadon-NOAA** [comment]
`FDATE` is mentioned in g-w PR #892 

- Add FDATE to config.base.emc.dyn

@KateFriedman-NOAA may recall the history of `FDATE`

**Comment by KateFriedman-NOAA** [comment]
`FDATE` was added to be set as the first full cycle in a cycled run with a half cycle (`SDATE`) preceding it (`FDATE`=`SDATE`+06). There was an IAU check that used to use it but it looks like that has been reworked so there may not be a need for `FDATE` anymore. I'm good with it being removed.

**Comment by lgannoaa** [comment]
@CoryMartin-NOAA 
May I know where is the expdir that you tested cycled experiment with older (pre GFSv16) ICs?
config.anal used FDATE to assign USE_RADSTAT on following conditions:
(1) Is this cycle is the first full cycle of a parallel run? 
(2) Is the EXP_WARM_START is set to false?
(3) I the current cycle is gfs or gdas?
exglobal_atmos_analysis.sh used variable USE_RADSTAT (dynamically assigned by the above logic) and CFP flag to untar radstat file. 
I can do a test for you to help debug why your run failed.

**Comment by CoryMartin-NOAA** [comment]
@lgannoaa I think this experiment has been long since lost. However it should be easily reproducible if the bug has not been fixed. When generating config.base from the workflow python script, is `FDATE` properly filled in? Judging by @KateFriedman-NOAA 's comment on 9/6, it seems like FDATE just needs to be removed.

**Comment by lgannoaa** [comment]
Chat with Cory offline and I to do a test in wcoss with c768/c384 to see if the error can be recreated.

**Comment by lgannoaa** [comment]
gdasanal job step start to run from the second cycle. It was not clear which cycle is the gdasanal job failed for the reporter.
An agreement has been set with the developer to run a flash test. This test using the develop branch #a9aaa580.
Setup expdir generate script as following:
python ./setup_expt.py cycled --idate 2021021918 --edate 2021022012 --app ATM --start cold --resdet 768 --resens 384 --gfs_cyc 4 --pslot gw-i-1005 \
                              --configdir /lfs/h2/emc/global/noscrub/${USER}/git/PR/ecf-archive/parm/config \
                              --comrot /lfs/h2/emc/ptmp/${USER} --expdir /lfs/h2/emc/global/noscrub/${USER}/expdir
Without indicate the first full cycle. Script setup_expt.py output:
- expdir/config.base:
    export FDATE=@FDATE@
  (this is the same behavior observed by the developer)
- ${pslot}.xml
    The first half cycle match the idate=2021021918.
    However, the first full cycle where gfs run is enabled is the next cycle 2021022000
    It assume the developer wants to run the first full cycle immediate following the first half cycle.

Analysis:
FDATE is used by analysis job by a known application logic to config USE_RADSTAT dynamically. The exglobal_atmos_analysis.sh job use USE_RADSTAT to proceed. 
File config.anal need FDATE to identify whether to enable USE_RADSTAT. The FDATE=@FDATE@ caused gdas analysis step failed to set USE_RADSTAT="NO" on the first full cycle.
Therefore, the job fail as indicated.

Recommend solution:
1. Update Global Workflow on-line document to clearly identify the need to set FDATE in config.base.
   URL: https://github.com/NOAA-EMC/global-workflow/wiki/
2. Modify setup_expt.py to generate message that identify the logic for generate first full cycle in xml file. Insert value into FDATE as needed.
3. The FDATE is needed for workflow because developer may want to start the first full cycle after a few more cycle after parallel started. It should not be removed.

**Comment by CoryMartin-NOAA** [comment]
What is the status of this? Seems it still has not been resolved in the workflow...
