### ISSUE TITLE
Preamble doesn't work properly when ex-script is non-shell

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [NOAA-EMC/global-workflow#1015]
The preamble.sh has on line 50:
```
  export PS4='+ $(basename $BASH_SOURCE)[$LINENO]'"$id: "  
```
This works great for .sh scripts, but it seems that when calling a .py script, I see things like this:
```
basename: missing operand
Try 'basename --help' for more information.
```
I suspect (but am not 100% sure) that the issue is this, in that `$BASH_SOURCE` only works for bash (presumably).

EE2 standards allow for bash, perl, and python, and we are moving towards a lot of python use, so it would be great if the preamble.sh supported at the minimum python ex-scripts. 

**Expected behavior**
The preamble should print out each script name regardless of interpreter.

**Current behavior**
```
basename: missing operand
Try 'basename --help' for more information.
```

**Machines affected**
Probably all, but on Orion is where I have found this

**To Reproduce**
Only is going to be noticed so far in my feature branch (feature/aeroda_jobs) when running ATMA in cycled mode.

**Possible Implementation**
Does changing `$BASH_SOURCE` to `$0` fix this? Or is this not going to give it the same behavior for the shell scripts? It may need to be rethought/turned off if calling a python ex-script vs bash/shell.

**Comment by CoryMartin-NOAA** [comment]
Yeah `$0` does not work as intended.... no surprise there

I tried `${BASH_SOURCE:-$0}` but that still isn't ideal I don't think, as it look like after the .py script runs, it doesn't return to the previous `$PS4`

**Comment by CoryMartin-NOAA** [comment]
Actually, this might be a `conda` related issue and not related to (but exposed by) the preamble. @aerorahul we need to figure out a way (unless it already is solved) to deal with virtual environments that is not conda-based because the conda shell commands that run under the hood are messy (and fail `set -e` due to unbound variables...)

**Comment by CoryMartin-NOAA** [comment]
Closing since 99% sure the issue is `conda` and not the preamble. It's unrealistic to expect a python script to use `$PS4` so the script's logging should be sufficient for identifying issues.

**Comment by bubba0077** [comment]
PS4 is a shell-specific setting that is only used for printing the trace (`set -x`). Python already has methods for doing this if necessary, though we do not use them in workflow. Since python automatically prints the calling trace when throwing an execution, it generally isn't necessary to print every line encountered (it also becomes messy as you descend into imported modules).

**Comment by bubba0077** [comment]
You are right though, conda does not play well with PS4 for some reason.

**Comment by bubba0077** [comment]
Though I haven't had problems running when using miniconda within workflow.

**Comment by CoryMartin-NOAA** [comment]
The `set -e` unbound issue comes from `$PROJ_LIB` or something like that, and is only if the virtual env includes python plotting (cartopy needs proj). This basename issue I have a hunch comes from actually this: https://github.com/NOAA-EMC/GDASApp/blob/d7c822b0e910ba49efedab3993f71980334d8704/modulefiles/GDAS/orion.lua#L58

Which, is probably something we should not be doing in a modulefile but rather in a workflow script.

**Comment by WalterKolczynski-NOAA** [comment]
Let me post that again from the right account:

PS4 is a shell-specific setting that is only used for printing the trace (set -x). Python already has methods for doing this if necessary, though we do not use them in workflow. Since python automatically prints the calling trace when throwing an execution, it generally isn't necessary to print every line encountered (it also becomes messy as you descend into imported modules).

You are right though, conda does not play well with PS4 for some reason. Though I haven't had problems running when using miniconda within workflow. IIRC, my issues occurred in the interactive shell (where PS4 isn't supposed to work) until I took out the modifications conda was making to my bashrc.

**Comment by WalterKolczynski-NOAA** [comment]
> Which, is probably something we should not be doing in a modulefile but rather in a workflow script.

I would agree with that. Yeah, setting PS4 is going to be a problem if the preamble is called from a non-shell script. Though maybe we should also have the preamble use "unknown" if `$BASH_SOURCE[1]` as `"undefined"` instead of failing.

**Comment by CoryMartin-NOAA** [comment]
> we should also have the preamble use "unknown" if `$BASH_SOURCE[1]` as `"undefined"` instead of failing.

Yeah I think that is a good solution. Printing a bunch of `basename missing operand` is just clutter, but `undefined` will at least keep it looking consistent in the logfile.
