### ISSUE TITLE
Post fails for low-resolution experiments

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#1060]
**Expected behavior**
Post should run for any resolution.

**Current behavior**
When running C96, post fails with a `too many MPI tasks, max is           96  stopping` message. Presumably UPP is limiting the number of ranks to the resolution (hold over from spectral?)

**Machines affected**
Discovered on Orion, but presumably on every machine.

**To Reproduce**
1. Set up any experiment using C96 resolution
2. Confirm the `gdaspost` and/or `gfspost` tasks fail in the first full cycle
3. Check the `outpost_gfs_${CDATE}_postcntrl_gfs_anl.xml` file in `${DATA}` to see the error message

**Comment by CoryMartin-NOAA** [comment]
I am not convinced this is fixed. 
A C96 experiment in rocoto had 3 nodes, 40 processors on Orion. 120 PEs, wich 96 < 120, so it failed. My guess is the config.resources did something like:
126 -> 96 (for resolution) but then 96/40 = 3 (because of 40 PEs/node on Orion)

@WalterKolczynski-NOAA would it be possible to confirm this is working as you intended it to be by an XML generation test only? Otherwise, I think the post scripts have to be modified to call `srun` with only the right number of PEs.

**Comment by WalterKolczynski-NOAA** [comment]
Yeah, I've seen it too. I have a fix I just need to submit it. In `env/ORION.env`, change `APRUN_NP` in the `post` section to `${launcher} -n ${npe_post}`

**Comment by CoryMartin-NOAA** [comment]
@WalterKolczynski-NOAA thanks, just wanted to make sure I wasn't going crazy/had a bad setup.

**Comment by WalterKolczynski-NOAA** [comment]
I think the fix _did_ work, but then subsequent updates forced a different solution.

**Comment by KateFriedman-NOAA** [comment]
Taking this on.

**Comment by KateFriedman-NOAA** [comment]
@CoryMartin-NOAA This should now be fixed. Let me know if you encounter further issues with the low-res post jobs.

**Comment by CoryMartin-NOAA** [comment]
Thank you @KateFriedman-NOAA  will do!!
