### ISSUE TITLE
C768 GDAS forecast OOM kill on Hera

### ISSUE THREAD

**Issue by TravisElless-NOAA** [NOAA-EMC/global-workflow#1121]
**Expected behavior**
 C768 simulations should successfully run on Hera when running with default resources. 

**Current behavior**
Initial GDAS forecast step fails; processes killed by out-of-memory handler

**Machines affected**
Hera

**Comment by KateFriedman-NOAA** [comment]
@TravisElless-NOAA Need more details. Can you share your xml and a log for the job that's dying from an OOM kill? Thanks!

**Comment by TravisElless-NOAA** [comment]
Sorry about that!

xml file: /scratch1/NCEPDEV/da/Travis.J.Elless/exp/full_res_30_mem/full_res_30_mem.xml
log file: /scratch2/NCEPDEV/stmp3/Travis.J.Elless/comrot/full_res_30_mem/logs/2022010312/gdasfcst.log

**Comment by KateFriedman-NOAA** [comment]
@TravisElless-NOAA Question...do you need to run C768? I ask for a few reasons: 1) it's expensive (compute and storage, particularly on Hera where memory is less per node) and 2) updates are coming soon to revamp things for esmf threading.

**Comment by TravisElless-NOAA** [comment]
@KateFriedman-NOAA what I really need is one full cycle with a C384 ensemble. I tried a C384/C384 run and that failed in the eobs step for a different reason. Would trying this on Orion be a better option?

**Comment by KateFriedman-NOAA** [comment]
@TravisElless-NOAA Ah ok I see. Yeah, Orion may work with the same resources since each node there has twice as much memory. Based on calculations and experience with C768 earlier this year on Hera, you'll likely need 50% more nodes on Hera for a C768 forecast job. Queues are also MUCH more open on Orion so even a 66 node job shouldn't wait long compared to how long it has been taking to get through the queues on Hera recently. If you don't mind, try on Orion and let me know if you get an OOM kill there. We generally discourage C768 outside of pre-implementation testing and outside of WCOSS2 (especially if not necessary to run that resolution) because of the resources used but if you're only running a single cycle then that's less impactful to the machine and other users.

**Comment by KateFriedman-NOAA** [comment]
@TravisElless-NOAA Is this issue still outstanding for you?

**Comment by TravisElless-NOAA** [comment]
Oh sorry I had this open still. I was able to get this run completed on the other machines so this isn't an outstanding issue for me.

**Comment by KateFriedman-NOAA** [comment]
No worries, thanks for closing! :)
