### ISSUE TITLE
AWIPS rocoto pre-job is calling multiple j-jobs

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#1228]
**Description**
The AWIPS rocoto pre-job (`jobs/rocoto/awips`) is calling multiple AWIPS j-jobs in succession. Each job should only be calling a single j-job.

**Requirements**
Likely need multiple AWIPS jobs in development to emulate operations. Alternatively, consolidate AWIPS under a single j-job.

**Acceptance Criteria (Definition of Done)**
One or more AWIPS rocoto jobs that each only call a single j-job during execution.

**Dependencies**
AWIPS capability should be restored to development first.

**Comment by GwenChen-NOAA** [comment]
The AWIPS rocoto pre-job (jobs/rocoto/awips.sh) is lacking the `JGFS_ATMOS_FBWIND` j-job, as a part of the GFS downstream wmo package. This issue is related to global-workflow issue #1221. The `JGFS_ATMOS_FBWIND` j-job can be either included in the AWIPS rocoto pre-job or a separated rocoto pre-job that runs when DO_AWIPS is turned on.
