### ISSUE TITLE
GDAS verify does not work on WCOSS2

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#1232]
**Expected behavior**
The gdasvrfy job should complete successfully on WCOSS2.

**Current behavior**
The gdasvrfy job fails on WCOSS2.

**Machines affected**
Currently a blocker for WCOSS2, but updating to newm 1.5 will impact all machines.

**To Reproduce**
1.  Setup a cycled experiment on WCOSS2
2. Watch gdasvrfy fail during the first full cycle

**Context**
There is no entry in the `config.vrfy` for the `$PREPQFITSH` (Fit2Obs) script. Develop is still using newm 1.3. While this version is on WCOSS2, it does not have a `subfits_` script for wcoss2, so it wouldn't run there anyway.

**Possible Implementation**
Update to newm 1.5, which is present on all three primary machines and add an entry for WCOSS2. The structure of the git directory has changed for 1.5, removing the `verif/global` from the path (instead of `${BASE_GIT}/verif/global/Fit2Obs/` it is now simply `${BASE_GIT}/Fit2Obs`. Also, the name of the script has changed, so instead of a big elif, the path can simply be `${fitdir}/subfits_${machine,,}`.

An initial test suggests additional downscript updates are required to update to 1.5, so it is not simply just pointing to the new path.

**Comment by WalterKolczynski-NOAA** [comment]
@EdwardSafford-NOAA @RussTreadon-NOAA

**Comment by KateFriedman-NOAA** [comment]
@WalterKolczynski-NOAA Apologies, I got behind the ball on updating us to the newer fit2obs.

For the `develop` branch moving to the `newm.1.5` version we'll want to update the `VRFYFITS` section of `config.vrfy` to match updates that happened in the GFSv16 branch. See here:
https://github.com/NOAA-EMC/global-workflow/blob/dev/gfs.v16/parm/config/config.vrfy#L35:L63

I have a copy of newm.1.5 installed under the global group account on supported platforms.

This `newm.1.5` version doesn't work in `develop` though, I think because of all the script cleanup and preamble improvements we made. I was able to do a quick change of the fit2obs scripts to bash and my updated copy on Cactus worked in a test. I didn't send this back to the fit2obs repo yet. Here is that copy on Cactus:

/lfs/h2/emc/global/noscrub/kate.friedman/git/FIT2OBS/newm.1.5

Here is my long-run high-res real-time test on WCOSS2 that used that copy of `newm.1.5` for fit2obs:

/lfs/h2/emc/global/noscrub/kate.friedman/expdir/devcyc768c/config.vrfy
/lfs/h2/emc/global/noscrub/kate.friedman/archive/devcyc768c/fits/
/lfs/h2/emc/global/noscrub/kate.friedman/archive/devcyc768c/horiz/*

I'm guessing needed updates will result in a version `newm.1.6` tag from the fit2obs repo. I think I warned @jack-woollen of incoming updates for this.

**Comment by jack-woollen** [comment]
@WalterKolczynski-NOAA @KateFriedman-NOAA the latest tag is newm.1.6 with some small updates requested for orion.

**Comment by KateFriedman-NOAA** [comment]
Created new fork branch for this work: https://github.com/KateFriedman-NOAA/global-workflow/tree/feature/fit2obs

Also created fork and branch for Fit2Obs changes: https://github.com/KateFriedman-NOAA/Fit2Obs/tree/feature/wcoss2_jet_support

FYI @DavidHuber-NOAA

**Comment by jack-woollen** [comment]
Let me know if I can help.

**Comment by KateFriedman-NOAA** [comment]
> Let me know if I can help.

Will do, thanks @jack-woollen ! Hoping to have test fit2obs output and logs for your review soon.

**Comment by KateFriedman-NOAA** [comment]
Fit2Obs issue: https://github.com/NOAA-EMC/Fit2Obs/issues/4

**Comment by KateFriedman-NOAA** [comment]
@DavidHuber-NOAA FYI for ff95dff commit for workflow side fit2obs changes.
