### ISSUE TITLE
[NCO Bug] Add restart capability for GFS atmos post processing jobs

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#1257]
Bugzilla [#1368](http://www2.spa.ncep.noaa.gov/bugzilla/show_bug.cgi?id=1368)

Details from NCO in bugzilla:
```
Please add the restart capability for GFS atmos gfs_atmos_postsnd job.

referred to the "NCEP Central Operations WCOSS Implementation Standards, version 11.0.0", page 13, 
https://www.nco.ncep.noaa.gov/idsb/implementation_standards/ImplementationStandards.v11.0.0.pdf?

During the catchup process after system issue, gfs atmos/wave post processing jobs could fail on waiting upstream 
files. Each time the gfs atmos/wave post processing jobs will processed from the very beginning. 

For the restart capability, suggest to add checking if the product is produced then skip logic in the jobs to avoid 
multiple alerts in rerun. Also it will be best use of the system resource and delivery product efficiently.
```

Related to issue #1251

**Comment by KateFriedman-NOAA** [comment]
@HuiyaChuang-NOAA @BoCui-NOAA @ShelleyMelchior-NOAA FYI

**Comment by HuiyaChuang-NOAA** [comment]
@KateFriedman-NOAA thanks.  
@ShelleyMelchior-NOAA I believe this one should be assigned to Bo as well but as Jason mentioned, Bo's
priority now is to finish NAEFS

**Comment by ShelleyMelchior-NOAA** [comment]
@KateFriedman-NOAA , please assign to @BoCui-NOAA .
Her priority is the code preparation and delivery of NAEFSv7. The code delivery target is Sep 2023.
She is aware of this bug and will work on it as she can.

**Comment by KateFriedman-NOAA** [comment]
Sounds good @ShelleyMelchior-NOAA , noted and thanks! We will absolutely need all bugzillas resolved in our repos before we start parallels, sooner would be best but no immediate rush. Will now assign this to @BoCui-NOAA .

**Comment by BoCui-NOAA** [comment]
Got the assigned task, thanks @KateFriedman-NOAA

**Comment by BoCui-NOAA** [comment]
Last week, Jessica, Cathy, and I discussed via email how to add restart capability to gfs_atmos_postsnd job.

Jessica gave helpful advice and offered two options. One is to make the job faster than 15 minutes so it doesn't need to be restarted. If this is not possible, save the information to a COM directory which can then be used in the restart job to rerun.

This is my option.  The option 2 is more practical. Due to the high resolution of the C1152, the runtime becomes longer than the current C768.  My plan is to save information ( log files) and midterm products to the COM directory. Once the re-run starts, the script will check and retrieve them to the new work directory.

${RUN}.${PDY}/$cyc/products/atmos/restart

Any suggestion to create a new directory "restart" list above? Thanks!

@aerorahul @WalterKolczynski-NOAA

**Comment by BoCui-NOAA** [comment]
@aerorahul @WalterKolczynski-NOAA 

I am working to add restart capability to gfs_atmos_postsnd job.  Some log files and midterm products must be saved and used once the re-run starts.  Is it ok to create restart directory under COM?

${RUN}.${PDY}/$cyc/products/atmos/restart

Please let me know, thanks!

**Comment by WalterKolczynski-NOAA** [comment]
@BoCui-NOAA other than the tarball at the end, is there any reason this needs to be run in a single job, or can we break it up and run it as a metatask at each forecast output time? Then a separate job to handle the tarball creation after they are all finished.

**Comment by BoCui-NOAA** [comment]
> @BoCui-NOAA other than the tarball at the end, is there any reason this needs to be run in a single job, or can we break it up and run it as a metatask at each forecast output time? Then a separate job to handle the tarball creation after they are all finished.

@WalterKolczynski-NOAA The executable in job gfs_atmos_postsnd is designed to process multiple hours' files simultaneously. For example, it reads in the files from 000 to 012 hours and outputs a temporary product file containing the information from 000hr to 012hr. Then start another time period from 013hr to 024hr and output another temporary output file. After all temporary output files are available, the same executable will process them and generate the final product file. If the job fails without temporary output files, the executable must start from the beginning at 000hr. That's why I asked for temporary files to be saved in the restart directory.

**Comment by BoCui-NOAA** [comment]
@WalterKolczynski-NOAA Temporary files use an estimated 934MB of space per cycle.

**Comment by WalterKolczynski-NOAA** [comment]
That's how it works _now_. What I'm asking is does it have to work that way or can we have each of those run a separate job like the other product jobs in the workflow instead of a loop. Essentially it would be separate jobs producing those temporary files instead of a loop. Saving the files is not an issue (though we will likely save them in STMP, not in COM).

**Comment by BoCui-NOAA** [comment]
> That's how it works _now_. What I'm asking is does it have to work that way or can we have each of those run a separate job like the other product jobs in the workflow instead of a loop. Essentially it would be separate jobs producing those temporary files instead of a loop. Saving the files is not an issue (though we will likely save them in STMP, not in COM).

@WalterKolczynski-NOAA  The code is intentionally generating these temporary files in a loop. Once the gfs data files for a period of time are available, the job starts executing. Then all the temporary files are combined together and finally some other processing steps are done. The idea of running separate jobs would result in the waiting for all gfs files and would require lots of modifications to the code.
 
Therefore, I recommend keeping the current job structure running and saving temporary files. It's a good idea to save them in STMP.  Are there any tips and requirements for creating directories in STMP?

**Comment by BoCui-NOAA** [comment]
https://github.com/NOAA-EMC/global-workflow/pull/2853

This PR has been approved and merged to global-workflow/develop.

The current operational BUFR job begins concurrently with the GFS model run. The above PR 2853 is to restructure the BUFR job script. The updated job will now start processing data only after the GFS model completes its 180-hour run, then handle all forecast files from 000hr to 180hr at a time. It eliminates waiting time and resource waste, and there’s no need to add a restart option to the script.
