### ISSUE TITLE
Gather ocean, ice output requirements for forecast only mode and update

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/global-workflow#1317]
**Description**
Implementation of model output for ocean and ice components for the prototypes has a conflict with the output requirements for cycled mode.  Cycling mode requires instantaneous output. 

At present the model produces a daily output and 6 hourly output (renamed with beginning and end of the interval)
`ocn_3D`, `ocn_2D`, `ocn-temp-EQ`, `ocn-uo-EQ` files are created from the 6 hourly output by doing `ncks` on them.
It appears that the model output is being split into a 2D and and 3D fields file.  Can this be done through the `diag_table` itself? 
The 3D `EQ` `temp` and currents `uo, vo` are further extracted from the 3D file.
`ocn_ice` is a product from `run_reg2grb2.sh`

This issue is to gather requirements from the coupled model for the output, frequency, accumulation, etc. and update the scripts.
The ocean model specifically outputs a variety of static fields repeatedly in the various collections via the `diag_table`. E.g. `geolon` etc.q
This leads to an increase in the filesizes over long forecast lengths.  
This will be corrected as part of this issue.

**Requirements**
- Clear description of requirements for the model output 
- Remove repeated static fields output
- update workflow scripts to improve data management

**Acceptance Criteria (Definition of Done)**
- Clear requirements of the model output, to make an informed decision across applications

**Comment by jiandewang** [comment]
@aerorahul 
(1) for "instantaneous output" do you mean save the final snapshot for every 6hr instead of 6hr averaging ? This can be done in diag_table setting
(2) I am more incline to think that save all the ocean fields in one file and get ride of 2D, 3D and EQ files. The original idea for splitting is for quick HPSS downloading when people's interesting is only focus on one particular topic. On the other hand, directly saved as 2D/3D files can be done in diag_table, pretty sure EQ files can also be done in diag_table (but never tried, may ask FMS group for help). This will have impact on ocean post as it is reading the whole files as input.
(3) removing geolat et. al will save ~6% space, not sure whether it will have impact on ocean post or not.

**Comment by aerorahul** [comment]
Thanks @jiandewang 
(2) I think the model is writing all the ocean fields in one file.  The 2D, 3D and EQ files are `ncks-ed` out from the "one" file in the `ocnpost` jobs.

**Comment by aerorahul** [comment]
Tagging @guillaumevernieres as he recently encountered issues in getting an output at the last forecast hour for his cycled system.  His issue is documented in https://github.com/NOAA-EMC/global-workflow/issues/1352
