### ISSUE TITLE
sorc/checkout.sh -u can not find GDASApp hash

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/global-workflow#1441]
**Expected behavior**
`sorc/checkout.sh -u` should clone GDASApp at the hash specified in the script. 

**Current behavior**
`checkout.sh` generates the following error message when executing the GDASApp clone

```
Performing checkout of gdas
|-- Cloning from https://github.com/NOAA-EMC/GDASApp.git into gdas.cd
|-- Checking out 6aa55fa
    WARNING: Error while checking out 6aa55fa in gdas
```

**Machines affected**
Found on Orion but affects all machines

**To Reproduce**

1. `mkdir test`
2. `cd test`
3. `clone g-w develop .`
5. `cd sorc`
6. `./checkout.sh -u`

**Detailed Description**
Attempts to load [https://github.com/NOAA-EMC/GDASApp/commit/6aa55fa](https://github.com/NOAA-EMC/GDASApp/commit/6aa55fa) return the warning
  
`  
This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.
   `

**Comment by TerrenceMcGuinness-NOAA** [comment]
Russ, I ran into a similar issue with git. We think in this case it might be a wrong hash in the check, as Kate was able to reproduce the error on Hera, can you do a` which git ` in a similar shell, we recommend you use **git/2.28.0** from the module load on Orion.

**Comment by RussTreadon-NOAA** [comment]
Use `git/2.28.0` (specifically `/apps/git-2.28.0/bin/git`) when executing `./checkout.sh -u` on Orion.

**Comment by TerrenceMcGuinness-NOAA** [comment]
Yes as recommended, Kate reminded me she has also document this specifically for Orion - thank you for the update.  I just stated on this issue now and will begin with reproducing the issue.  I assigned myself to this because I have a set of Continuous Integration scripts that can help us with these type of issues.

**Comment by RussTreadon-NOAA** [comment]
[GDASApp PR #406](https://github.com/NOAA-EMC/GDASApp/pull/406) references [6aa55fa](https://github.com/NOAA-EMC/GDASApp/commit/6aa55facdf12cf3f030e44ba55b178748153f8d8).   

@CoryMartin-NOAA , any idea why this hash _does not belong to any branch on this repository_?  Does this has point at a fork outside the GDASApp repo?

**Comment by TerrenceMcGuinness-NOAA** [comment]
@RussTreadon-NOAA submitted the changes to the checkout.sh script #1443 and added @CoryMartin-NOAA as a reviewer and confirmed with @aerorahul  for the update of the HASH for this.

**Comment by CoryMartin-NOAA** [comment]
I think I know what the issue is, unfortunately this means I need to come up with a new/alternative solution for GDASApp feature/stable-nightly. The branch is deleted and re-created every day with updated JEDI hashes, but I guess that means the hash is deleted too, not just the branch... Let me create a new branch with a hash for people to point to for now until I figure out a better solution. Stand by (I'll put the hash in a comment on #1443)
