### ISSUE TITLE
Task gdasanal failed on C384 gdas cycle run

### ISSUE THREAD

**Issue by jiaruidong2017** [NOAA-EMC/global-workflow#1738]
I'm running the C384 gdas cycle tests. The task `gdasanal` failed with the following error messages:

```
 44: Load the cloud coefficients:
 44: ...Cloud model: CRTM
 44: ...CloudCoeff file: ./crtm_coeffs/CloudCoeff.bin
116: forrtl: severe (174): SIGSEGV, segmentation fault occurred
116: Image              PC                Routine            Line        Source
116: gsi.x              00000000021A80DD  Unknown               Unknown  Unknown
116: libpthread-2.17.s  00002B90BA5B9630  Unknown               Unknown  Unknown
116: libiomp5.so        00002B90B8BB4FD1  Unknown               Unknown  Unknown
116: libiomp5.so        00002B90B8BB4D44  Unknown               Unknown  Unknown
116: libiomp5.so        00002B90B8BB6B55  Unknown               Unknown  Unknown
116: libiomp5.so        00002B90B8BADDE4  Unknown               Unknown  Unknown
116: libiomp5.so        00002B90B8BB02BB  Unknown               Unknown  Unknown
116: gsi.x              00000000021EA19A  Unknown               Unknown  Unknown
116: gsi.x              0000000002190FB8  Unknown               Unknown  Unknown
116: gsi.x              0000000002190EA0  Unknown               Unknown  Unknown
116: gsi.x              0000000002190EA0  Unknown               Unknown  Unknown
116: gsi.x              000000000150283A  crtm_interface_mp         950  crtm_interface.f90
116: gsi.x              00000000012BCA49  rad_setup_mp_setu        2188  setuprad.f90
116: gsi.x              0000000000EDA1CA  gsi_radoper_mp_se         100  gsi_radOper.F90
116: gsi.x              0000000000A937EC  setuprhsall_              490  setuprhsall.f90
116: gsi.x              0000000000EC0D28  glbsoi_                   323  glbsoi.f90
116: gsi.x              0000000000626E39  gsisub_                   200  gsisub.F90
116: gsi.x              00000000004088BD  gsimod_mp_gsimain        2311  gsimod.F90
116: gsi.x              00000000004087FF  MAIN__                    631  gsimain.f90
116: gsi.x              000000000040879E  Unknown               Unknown  Unknown
116: libc-2.17.so       00002B90BB0A1555  __libc_start_main     Unknown  Unknown
116: gsi.x              00000000004086A9  Unknown               Unknown  Unknown
```
I drop the entire log file at the bottom for your review. It seems this failing due to out of memory again. The computing resource were listed below: 

```
<task name="gdasanal" cycledefs="gdas" maxtries="&MAXTRIES;">

        <command>&JOBS_DIR;/anal.sh</command>

        <jobname><cyclestr>&PSLOT;_gdasanal_@H</cyclestr></jobname>
        <account>fv3-cpu</account>
        <queue>batch</queue>
        <partition>hera</partition>
        <walltime>00:50:00</walltime>
        <nodes>40:ppn=4:tpp=10</nodes>
        <native>--export=NONE</native>

        <join><cyclestr>&ROTDIR;/logs/@Y@m@d@H/gdasanal.log</cyclestr></join>
```
[gdasanal.log](https://github.com/NOAA-EMC/global-workflow/files/12053307/gdasanal.log)

**Comment by aerorahul** [comment]
@jiaruidong2017 
Please reach out to someone on the DA development tram to seek a recommendation on appropriate resources for this job at this resolution.

Looking at the log, I highly doubt this is a memory issue as it has completed 59 iterations.  There must be something else at play.

Also, please use the [Bug Report template](https://github.com/NOAA-EMC/global-workflow/issues/new?assignees=&labels=bug&projects=&template=bug_report.md) when opening an issue if this is a Bug in the workflow.

**Comment by jiaruidong2017** [comment]
Thanks @aerorahul for your suggestions. I will use the Bug Report template next time. 
@CoryMartin-NOAA @RussTreadon-NOAA Do you have any suggestions on the assigned appropriate resources. Thanks.

**Comment by RussTreadon-NOAA** [comment]
I agree with Rahul.   I don't think this is a memory issue.   The log file shows that the first outer loop of 100 iterations completed.   The code is back in the hofx section prior to the start of the second outer loop.   The traceback points to different lines for different tasks.  It's not clear which task(s) is/are responsible for the seg fault.   

If you think job resource allocation is the problem, change the resource allocation.  You are currently running 160 tasks with 4 tasks per node with 10 threads per task according to the `anal` section of your `config.resources`
```
      export npe_anal=160
      export npe_anal_gfs=160
      export nth_anal=10
      export nth_anal_gfs=10
```
You could double or triple the task count, `npe_anal`.    Regenerate the xml after you edit `config.resources` and rerun the failed job.

If the problem is not resource, something has gone bad in the code.  In this case you need to debug the gsi.   Look at the lines found in the traceback.  See if anything looks unusual.   You may need to add prints, recompile, and rerun.   This will lead to more prints and more runs until the source of the problem is found.   Once found and understood, start working on a solution.  This can be a tedious effort.

Attaching the log file to the issue is informative but there's not much one can do with it when it comes to debugging.  It is more helpful to share the path to the log file:  `/scratch1/NCEPDEV/global/Jiarui.Dong/ptmp/landid9/logs/2021032306/gdasanal.log`.   Examination of the log file inevitably leads to looking at other stuff (gsi source code, input files, run directory, etc).   This requires you/others to log onto Hera and poke around.

**Comment by jiaruidong2017** [comment]
@RussTreadon-NOAA Thank you for the detailed instructions, and I will try to rerun with the increased resources. 
I previously conducted the C96 tests yesterday, and all test runs were completed without any issues. In addition, I have successfully completed the C384 test runs by using the global-workflow version on June 23rd. I am not sure if there is any changes in `gdasanal` from last month.

**Comment by jiaruidong2017** [comment]
When I increased the resources to the 640 tasks with 8 tasks per node with 5 threads per task as below,  

```
      export npe_anal=640
      export npe_anal_gfs=640
      export nth_anal=5
      export nth_anal_gfs=5
```
The run still failed. Therefore, the problem doesn't seem to be resource issues.
