### ISSUE TITLE
Missing fix file in support of EP4 

### ISSUE THREAD

**Issue by bbakernoaa** [NOAA-EMC/global-workflow#1833]
### Target fix directory

chem

### Type of change

- [ ] Update existing files
- [ ] Remove files
- [X] Add new files to existing directory
- [ ] Add new fix directory

### Any workflow changes needed?

Fix version only

### Pickup location

/scratch1/RDARCH/rda-arl-gpu/Barry.Baker/emissions/nexus/CEDS/v2019/2013/CEDS.2019.20131231.nc /scratch1/RDARCH/rda-arl-gpu/Barry.Baker/emissions/nexus/CEDS/v2019/2016/CEDS.2019.20161231.nc /scratch1/RDARCH/rda-arl-gpu/Barry.Baker/emissions/nexus/CEDS/v2019/2017/CEDS.2019.20171231.nc /scratch1/RDARCH/rda-arl-gpu/Barry.Baker/emissions/nexus/CEDS/v2019/2018/CEDS.2019.20181231.nc

### Size

65

**Comment by WalterKolczynski-NOAA** [comment]
These file names do not match the filenames in these actual directories:

```
[role.glopara@hfe09 gocart_emissions]$ ls /scratch1/RDARCH/rda-arl-gpu/Barry.Baker/emissions/nexus/CEDS/v2019/2013/CEDS.2019.emis.2013123*
/scratch1/RDARCH/rda-arl-gpu/Barry.Baker/emissions/nexus/CEDS/v2019/2013/CEDS.2019.emis.20131230.nc
/scratch1/RDARCH/rda-arl-gpu/Barry.Baker/emissions/nexus/CEDS/v2019/2013/CEDS.2019.emis.20131231.nc
```

The global version of these directories already have these files.
```
[role.glopara@hfe09 gocart_emissions]$ ls nexus/CEDS/v2019/*/*1231.nc
nexus/CEDS/v2019/2011/CEDS.2019.emis.20111231.nc  nexus/CEDS/v2019/2016/CEDS.2019.emis.20161231.nc
nexus/CEDS/v2019/2012/CEDS.2019.emis.20121231.nc  nexus/CEDS/v2019/2017/CEDS.2019.emis.20171231.nc
nexus/CEDS/v2019/2013/CEDS.2019.emis.20131231.nc  nexus/CEDS/v2019/2018/CEDS.2019.emis.20181231.nc
nexus/CEDS/v2019/2014/CEDS.2019.emis.20141231.nc  nexus/CEDS/v2019/2019/CEDS.2019.emis.20191231.nc
nexus/CEDS/v2019/2015/CEDS.2019.emis.20151231.nc  nexus/CEDS/v2019/2020/CEDS.2019.emis.20201231.nc
```

**Comment by bingfu-NOAA** [comment]
@WalterKolczynski-NOAA The issue is there are missing files (for the day 12/31) for year 2013,2016,2017 and 2018 on WCOSS2.
/lfs/h2/emc/global/noscrub/emc.global/data/gocart_emissions/nexus/CEDS/v2019
[dogwood@dlogin03 v2019]$ ls -l */*1231.nc*
-rw-r--r-- 1 emc.global global 15244766 Aug 11  2022 2011/CEDS.2019.emis.20111231.nc
-rwxrwxr-x 1 emc.global global 15249664 May 16  2022 2012/CEDS.2019.emis.20121231.nc
-rw-r--r-- 1 emc.global global 15257565 Aug 11  2022 2014/CEDS.2019.emis.20141231.nc
-rw-r--r-- 1 emc.global global 15256702 Aug 11  2022 2015/CEDS.2019.emis.20151231.nc
-rwxrwxr-x 1 emc.global global 15251887 May 16  2022 2019/CEDS.2019.emis.20191231.nc
-rwxrwxr-x 1 emc.global global 15254158 May 16  2022 2020/CEDS.2019.emis.20201231.nc

**Comment by WalterKolczynski-NOAA** [comment]
The missing files should be available on WCOSS now.
