### ISSUE TITLE
Snow DA cycling experiment broken in the hybrid run

### ISSUE THREAD

**Issue by jiaruidong2017** [NOAA-EMC/global-workflow#1938]
### What is wrong?

When I conducted the hybrid run, the snow DA cycling task `gdaslandanl` was broken as below: 

![image](https://github.com/NOAA-EMC/global-workflow/assets/27369703/22f5c7b0-46e7-4307-9161-0668be5984bf)

The detailed logfile is attached here: 
[gdaslandanl.log](https://github.com/NOAA-EMC/global-workflow/files/13035339/gdaslandanl.log)

### What should have happened?

The `gdaslandanl` task should run successfully. 

### What machines are impacted?

Hera

### Steps to reproduce

Work directory: /scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GlobalWorkflow/para_gfs/landid9/

Run directory: /scratch1/NCEPDEV/stmp2/Jiarui.Dong/RUNDIRS/landid9/

Log directory: /scratch1/NCEPDEV/climate/Jiarui.Dong/ptmp/landid9/logs/

### Additional information

NA

**Comment by RussTreadon-NOAA** [comment]
@jiaruidong2017 , `gdaslandanl.log` identifies the problem.   The error message states that there is a library mismatch
```
The warning messages in the log file highlight the problem
 41: Warning! ***HDF5 library version mismatched error***
 41: The HDF5 header files used to compile this application do not match
 41: the version used by the HDF5 library to which this application is linked.
 41: Data corruption or segmentation faults may occur if the application continues.
 41: This can happen when an application was compiled by one version of HDF5 but
 41: linked with a different version of static or shared HDF5 library.
 41: You should recompile the application or check your shared library related
 41: settings such as 'LD_LIBRARY_PATH'.
 41: You can, at your own risk, disable this warning by setting the environment
 41: variable 'HDF5_DISABLE_VERSION_CHECK' to a value of '1'.
 41: Setting it to 2 or higher will suppress the warning messages totally.
 41: Headers are 1.14.0, library is 1.12.2
 41:         SUMMARY OF THE HDF5 CONFIGURATION
 41:         =================================
 41:
 41: General Information:
 41: -------------------
 41:                    HDF5 Version: 1.12.2
 41:                   Configured on: 2023-04-20
```
The environment has `hdf5/1.14.0` but `fv3jedi_letkf.x` is looking for `hdf5/1.12.2`

How did this happen?   

According to `build_gdas.log` in `/scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GlobalWorkflow/global-workflow.landid9/sorc/logs`, `hdf5/1.12.2` was loaded when code in `sorc/gdas.cd` was built.   However, `sorc/gdas.cd/modulefiles/GDAS/hera.lua` loads `hdf5/1.14.0`.   

This suggests that when you updated your working copy of `feature/madis_da2`, you did not rebuild GDASApp executables.   A check of date-time stamps shows
```
Hera(hfe03):/scratch1/NCEPDEV/global/Jiarui.Dong/JEDI/GlobalWorkflow/global-workflow.landid9/sorc/gdas.cd$ ls -l build/bin/fv3jedi_letkf.x modulefiles/GDAS/hera.lua
-rwxr-xr-x 1 Jiarui.Dong global 64169792 Oct 12 14:26 build/bin/fv3jedi_letkf.x
-rw-r--r-- 1 Jiarui.Dong global     2570 Oct 12 17:20 modulefiles/GDAS/hera.lua
```
File `hera.lua` has a date-time stamp _after_ the date-time stamp for `fv3jedi_letkf.x`.   

`ldd fv3jedi_letkf.x` confirms that it was built with `hdf5/1.12.2`
```
        libhdf5_hl.so.200 => /scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.3.1/envs/unified-env/install/intel/2021.5.0/hdf5-1.12.2-7w4b7vi/lib/libhdf5_hl.so.200 (0x00007f85fefc8000)
        libhdf5.so.200 => /scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.3.1/envs/unified-env/install/intel/2021.5.0/hdf5-1.12.2-7w4b7vi/lib/libhdf5.so.200 (0x00007f85fe849000)
```
When `gdaslandanl` runs it loads `GDAS/hera.lua`.   Thus, `hdf/1.14.0` is loaded.  Since  `fv3jedi_letkf.x` was built with `hdf5/1.12.2`, library mismatch messages are written to `gdaslandanl.log`   

This is not a bug.  This appears to be an oversight when updating the working copy of your branch.

You need to rebuild executables in `sorc/gdas.cd`.

**Comment by jiaruidong2017** [comment]
@RussTreadon-NOAA Thank you very much for the thorough explanations and directions.  Following your suggestions, I rebuilt the GDASApp and checked the `hdf/1.14.0` is loaded. Then I rerun my gdaslandanl task, and it worked perfectly. Again, thank you very much for your help.

**Comment by aerorahul** [comment]
#1821
