### ISSUE TITLE
Update global lake data

### ISSUE THREAD

**Issue by GeorgeGayno-NOAA** [NOAA-EMC/global-workflow#1984]
### Target fix directory

raw

### Type of change

- [X] Update existing files
- [X] Remove files
- [X] Add new files to existing directory
- [ ] Add new fix directory

### Any workflow changes needed?

No change needed

### Related issues

https://github.com/ufs-community/UFS_UTILS/issues/854

### Pickup location

Hera: /home/Shan.Sun/tmp_lake_txt

### Size

No difference.

**Comment by GeorgeGayno-NOAA** [comment]
Implementation details:

Rename two existing files:
- `mv GlobalLakeDepth.dat GlobalLakeDepth_GLDBv2release.dat`
- `mv GlobalLakeStatus.dat GlobalLakeStatus_GLDBv2release.dat`

Remove the following files:
- `GlobalLakeDepth.txt` 
- `GlobalLakeStatus.txt`

Replace the two removed files with the four files here:

- `cp /home/Shan.Sun/tmp_lake_txt/GlobalLake*.txt  .`

**Comment by GeorgeGayno-NOAA** [comment]
FYI: @shansun6 and @NingWang325

**Comment by KateFriedman-NOAA** [comment]
Working on this...making a new `orog` timestamp for this and issue #1981.

**Comment by KateFriedman-NOAA** [comment]
@GeorgeGayno-NOAA Done as requested, thanks for the concise instructions. Please see the new `orog/20231027` timestamp on Hera and confirm it is correct:

```
[role.glopara@hfe04 20231027]$ pwd
/scratch1/NCEPDEV/global/glopara/fix/orog/20231027
[role.glopara@hfe04 20231027]$ ll GlobalLake*
-rw-r--r-- 1 role.glopara global 1866240000 May 31  2018 GlobalLakeDepth_GLDBv2release.dat
-rw-r--r-- 1 role.glopara global       2191 Oct 25 17:59 GlobalLakeDepth_GLDBv2release.txt
-rw-r--r-- 1 role.glopara global       2695 Oct 25 19:02 GlobalLakeDepth_GLDBv3release.txt
-rw-r--r-- 1 role.glopara global  933120000 May 31  2018 GlobalLakeStatus_GLDBv2release.dat
-rw-r--r-- 1 role.glopara global       2845 Oct 25 18:42 GlobalLakeStatus_GLDBv2release.txt
-rw-r--r-- 1 role.glopara global       4185 Oct 25 17:54 GlobalLakeStatus_GLDBv3release.txt
```

Note: I did not touch the files in the `raw/orog` folder which were previously being symlinked to from `orog` for the GlobalLake files. I left them as is and still being symlinked to from the older `20230615` timestamp copy.

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA Done as requested, thanks for the concise instructions. Please see the new `orog/20231027` timestamp on Hera and confirm it is correct:
> 
> ```
> [role.glopara@hfe04 20231027]$ pwd
> /scratch1/NCEPDEV/global/glopara/fix/orog/20231027
> [role.glopara@hfe04 20231027]$ ll GlobalLake*
> -rw-r--r-- 1 role.glopara global 1866240000 May 31  2018 GlobalLakeDepth_GLDBv2release.dat
> -rw-r--r-- 1 role.glopara global       2191 Oct 25 17:59 GlobalLakeDepth_GLDBv2release.txt
> -rw-r--r-- 1 role.glopara global       2695 Oct 25 19:02 GlobalLakeDepth_GLDBv3release.txt
> -rw-r--r-- 1 role.glopara global  933120000 May 31  2018 GlobalLakeStatus_GLDBv2release.dat
> -rw-r--r-- 1 role.glopara global       2845 Oct 25 18:42 GlobalLakeStatus_GLDBv2release.txt
> -rw-r--r-- 1 role.glopara global       4185 Oct 25 17:54 GlobalLakeStatus_GLDBv3release.txt
> ```
> 
> Note: I did not touch the files in the `raw/orog` folder which were previously being symlinked to from `orog` for the GlobalLake files. I left them as is and still being symlinked to from the older `20230615` timestamp copy.

UFS_UTILS is pointing to `/scratch1/NCEPDEV/global/glopara/fix/raw/orog` for the GlobalLake files. Is the long-term plan to move these files to `orog`? What will be the future of the `raw/orog` directory?

**Comment by KateFriedman-NOAA** [comment]
> UFS_UTILS is pointing to /scratch1/NCEPDEV/global/glopara/fix/raw/orog for the GlobalLake files.

@GeorgeGayno-NOAA Hmmmmmm. I did not want to touch the ones sitting in the current `raw/orog` since older versions of `orog` point to them. Since the `raw/orog` folder is not versioned but the `orog` folder is, I placed the new files (and renamed them) in the new `orog/20231027` subfolder. I see these options:

1. UFS_UTILS moves to point to `orog/${orog_ver}` instead for the GlobalLake files.
2. We introduce versioning into the `raw/orog` folder (UFS_UTILS would also need to introduce versioning into the path for the GlobalLake files). Along with this we'd need to add symlinks from the new `orog/20231027` folder to see the new GlobalLake files in `raw/orog/${raw_orog_ver}`.
3. We add the new files (with the new names) into the `raw/orog` folder and retain the prior named versions to support the older `orog` version. Would also need symlinks in the new `orog/20231027` folder for the new GlobalLake files. Your instructions stated to move away from the `GlobalLakeDepth.txt` and `GlobalLakeStatus.txt` so I did what I described above. :)

Let me know if there is another option I haven't considered. My vote would be either option 1 or 3, option 1 in particular to avoid further complicating the `orog` and `raw/orog` files but that's my view from the fix file mangement side of things. :)

> What will be the future of the raw/orog directory?

Good question and not one I can answer. @yangfanglin any thoughts or who else we should discuss this with?

**Comment by GeorgeGayno-NOAA** [comment]
Ok. I would have guessed that anything in `raw` would be used to create the model data in `orog`. But that would point to option 2. 

UFS_UTILS will follow whatever you decide.

**Comment by WalterKolczynski-NOAA** [comment]
I would strongly favor `#1`. I don't see the point of having a separate `raw` fix directory if it is just holding stuff that really belongs in `orog`.

**Comment by WalterKolczynski-NOAA** [comment]
Actually, now I'm looking at #1206, and my suggestion here in particular: https://github.com/NOAA-EMC/global-workflow/issues/1206#issuecomment-1372939518

That issue was never completed. We should wrap up that issue as part of this new `orog`.
