### ISSUE TITLE
Archive jobs failing to find sbuv2_n19 ozone data

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/global-workflow#2076]
### What is wrong?

The `gdasarch` job looks for a few ozone monitor outputs when `DO_VERFOZN="YES"` based on a hard-coded list in hpssarch_gen.sh, including `sbuv2_n19`.  However, SBUV/2 data on NOAA 19 stopped producing data in 2013, so there is no data available to verify/monitor leading to `gdasarch` to fail because the `htar` command cannot find it.

### What should have happened?

The archiving job should be able to look for only the instruments available.  There will be times when other instruments fail or are offline briefly and the job should continue to archive what is available without error.

### What machines are impacted?

All or N/A

### Steps to reproduce

Run a full analysis cycle and look for htar error reported in gdasarch.log.

### Additional information

Found during spack-stack testing.

### Do you have a proposed solution?

The htar command to archive gdas.tar (where the monitor files are pushed to) should either be split up into a baseline set of data (the data that should always be produced by the workflow) and an auxiliary set (including the monitoring data).  Archive the baseline set first, then append to the archive with the auxiliary set.  Errors should be produced for members not present in the baseline set while warnings should be produced for data not present in the auxiliary.

**Comment by KateFriedman-NOAA** [comment]
Looks like I got lucky with my testing when I added the GSI monitor output to the archival step in issue #1908. I actually asked Ed about the `sbuv2_n19` data: https://github.com/NOAA-EMC/global-workflow/issues/1908#issuecomment-1777808601. It was available in my test output, see the comment a bit further down: https://github.com/NOAA-EMC/global-workflow/issues/1908#issuecomment-1777966608. I further discussed which types to expect, put in the hard-coded list, and pushed further enhancement to a follow-up issue. Looks like that follow-up issue is needed now since those `sbuv2_n19

**Comment by KateFriedman-NOAA** [comment]
Oops, fat finger, sorry!

**Comment by KateFriedman-NOAA** [comment]
Looks like I got lucky with my testing when I added the GSI monitor output to the archival step in issue #1908. I actually asked Ed about the `sbuv2_n19` data: https://github.com/NOAA-EMC/global-workflow/issues/1908#issuecomment-1777808601. It was available in my test output, see the comment a bit further down: https://github.com/NOAA-EMC/global-workflow/issues/1908#issuecomment-1777966608. I further discussed which types to expect, put in the hard-coded list, and pushed further enhancement to a follow-up issue. Looks like that follow-up issue is needed now since those `sbuv2_n19` aren't always available.
