### ISSUE TITLE
Support multiple APP for GFSv17 

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#2318]
### What new functionality do you need?

Be able to use different values of APP for different forecast jobs. 

### What are the requirements for the new functionality?

Currently for GFSv17 the plan is to have 3 different apps for different forecasts: 

gfs forecast APP=S2SW 
gdas forecast APP=S2SWA 
enkfgdas forecast APP=S2S

While all these apps can use the same executable, we will need to configure each of these forecasts to run with different components. 

### Acceptance Criteria

Be able to configure and run with three different apps for the various forecat jobs.

**Comment by CoryMartin-NOAA** [comment]
Just as a follow up requirement:

Currently the aerosol analysis runs dependent on the 'app' chosen. But we will need a GDAS aero analysis and a GFS aero analysis (to initialize the GEFS) even if the GFS forecast app is not S2SWA. So we will need some sort of switch that says:
if APPgdas has aero, gfs cycle has aero analysis...

**Comment by DavidHuber-NOAA** [comment]
As is, aerosol analyses/forecasts are not being run if `APP` includes "`A`".  This is because `setup_xml.py` sources `config.base` with `RUN=gfs`, causing the `A` to be trimmed by
https://github.com/NOAA-EMC/global-workflow/blob/a005244bbfb2f1c525bca60d966f8095aa1acb8e/parm/config/gfs/config.base#L165-L168

A sample test case of `C96_atmaerosnowDA` is available in `/scratch1/NCEPDEV/global/David.Huber/noscrub/test_snow`.  `test_snow.xml` does not contain any aerosol jobs.

First reported by @CoryMartin-NOAA [here](https://github.com/NOAA-EMC/global-workflow/pull/2413#issuecomment-2035043546).

**Comment by DavidHuber-NOAA** [comment]
I'm going to try and fix this as part of #2491, though it may need to be handled separately if there are any issues with the aerosol jobs.
