### ISSUE TITLE
Refactor archiving to handle missing files and failures appropriately

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/global-workflow#2345]
### What new functionality do you need?

The archive scripts should handle missing data correctly.  Missing required files (or other htar failures) should cause failures with clear messages while missing optional files should either generate a warning (in some cases) or simply skip by them.

### What are the requirements for the new functionality?

All files that need to be archived need to be identified as required or optional and if optional if a warning needs to be issued if they are missing.

### Acceptance Criteria

All archived files are identified and handled appropriately and all `tar` and `htar` errors are handled correctly.

**Comment by DavidHuber-NOAA** [comment]
This issue consolidates and replaces #2340 and #2242.

**Comment by WalterKolczynski-NOAA** [comment]
Thanks @DavidHuber-NOAA

**Comment by JessicaMeixner-NOAA** [comment]
> This issue consolidates and replaces #2340 and #2242.

If this is going to replace 2242, this issue needs to be updated to address the additional failures beyond missing files.  For example, 2242 is about the fact that I tried to write to an hpss directory i did not have access to.    A newer issue to the workflow is about the fact that the htar failed due to file size.  This issue currently does not reflect these other failure cases that are also important to address.

**Comment by WalterKolczynski-NOAA** [comment]
Updated to reflect other htar errors should also cause a failure.

**Comment by JessicaMeixner-NOAA** [comment]
Can the acceptance criteria reflect that the job should fail if HTAR fails?  As of now I still don't think this issue is really covering the issues described in 2242 and therefore request that this be updated further or that the other issue is reopened.

**Comment by DavidHuber-NOAA** [comment]
@JessicaMeixner-NOAA Thanks, I've updated the acceptance criteria.
