### ISSUE TITLE
infrared cloud detection scheme fix files

### ISSUE THREAD

**Issue by wx20jjung** [NOAA-EMC/global-workflow#2474]
### Target fix directory

gsi

### Type of change

- [ ] Update existing files
- [ ] Remove files
- [X] Add new files to existing directory
- [ ] Add new fix directory

### Any workflow changes needed?

Fix version + additional changes

### Related issues

This is part of global-workflow ticket #2473 (infrared cloud detection scheme).  These file should be added to the gsi fix directory along with changes to #2473.  The files reside on hera:/scratch1/NCEPDEV/jcsda/Jim.Jung/save/global-workflow/fix
-rwxr-xr-x 1 Jim.Jung jcsda 1106 Apr  9 16:13 AIRS_CLDDET.NL
-rwxr-xr-x 1 Jim.Jung jcsda 2510 Apr  9 16:13 CRIS_CLDDET.NL
-rwxr-xr-x 1 Jim.Jung jcsda 1623 Apr  9 16:13 IASI_CLDDET.NL

### Pickup location

hera:/scratch1/NCEPDEV/jcsda/Jim.Jung/save/global-workflow/fix

### Size

files are less than 1MB

**Comment by KateFriedman-NOAA** [comment]
@wx20jjung Since these are GSI fix files we need to get them added to the [GSI-fix repo](https://github.com/NOAA-EMC/GSI-fix) first and then I can do a new install of the GSI fix within the full fix set (and update the timestamp version for `gsi_ver` in `versions/fix.ver` alongside that). Tagging @RussTreadon-NOAA for his feedback on the procedure to add new fix files to GSI-fix.

**Comment by KateFriedman-NOAA** [comment]
The requested files were added to the latest GSI fix timestamp. Related issue is now closed. Closing this as complete.
