### ISSUE TITLE
CICE 100 files on hera are incorrect 

### ISSUE THREAD

**Issue by NeilBarton-NOAA** [NOAA-EMC/global-workflow#2595]
### Target fix directory

cice

### Type of change

- [X] Update existing files
- [ ] Remove files
- [ ] Add new files to existing directory
- [ ] Add new fix directory

### Any workflow changes needed?

Fix version + additional changes

### Related issues

On hera, the files at 
/scratch1/NCEPDEV/global/glopara/fix/cice/20231219/100

are files for MOM6 and not CICE. However, the files for cice_ver=20240416 are correct. 

Please update the cice/20231219/100 files or change the cice_ver to 20240416

### Pickup location

/scratch1/NCEPDEV/global/glopara/fix/cice/20240416/100

### Size

12M

**Comment by KateFriedman-NOAA** [comment]
> Please update the cice/20231219/100 files or change the cice_ver to 20240416

@NeilBarton-NOAA In this situation we should go with the latter option (change to `cice_ver=20240416`) since we generally avoid changing existing files and instead would incorporate the updated files in a new timestamp...so we don't impact users using the existing files. However, we were waiting to move to the new cice set once a UWM PR went in ([see this g-w issue 2483 comment](https://github.com/NOAA-EMC/global-workflow/issues/2483#issuecomment-2077995145))...

@DeniseWorthen I see that PR was merged...do we need to go to that new hash of UWM when we move to the `20240416` cice fix set or can we move to the newer cice fix set now?

**Comment by DeniseWorthen** [comment]
@KateFriedman-NOAA I'm not really clear on how all this is coordinated and aligned. But, yes, if you want both the RT and the G-W to use the same CICE fix files then you should update the hash when you use the new fix files. (There were no actual code changes w/ the hash update, just pointing to the new input-data.)

As for the CICE 100 files, I had also created an issue #2480 about a month ago. I think anyone trying to use that set of files will have a failure in the g-w, since it won't actually find CICE files where it is looking for them, right? I don't know how to solve that, other than changing the cice_ver as you suggest.

**Comment by KateFriedman-NOAA** [comment]
@DeniseWorthen Thanks for your feedback. I discussed this with @WalterKolczynski-NOAA and we will move g-w `develop` to the newer `cice/20240416` timestamp. That will resolve this issue and close #2480 in the process. We'll run CI tests to make sure things are ok. Let us know if you have any objections, thanks!
