### ISSUE TITLE
Add a flag checking the file existence for the snocvr observation data

### ISSUE THREAD

**Issue by jiaruidong2017** [NOAA-EMC/global-workflow#2828]
### What new functionality do you need?

Operational `snocvr` dump files are available from December 3, 2022. Prior to this date, the `snocvr` observation data in the ioda format should be provided for the G-W snow DA test. Therefore, we propose to add a flag checking the file existence to avoid the G-W run crashes when the `snocvr` files are not found. 

### What are the requirements for the new functionality?

Add checking the file existence.

### Acceptance Criteria

Run the G-W snow DA test at any time even without snocvr data available.

**Comment by jiaruidong2017** [comment]
FYI @ClaraDraper-NOAA @CoryMartin-NOAA

**Comment by aerorahul** [comment]
@jiaruidong2017 can you explain where this flag needs to be added?  Is this a config option?

**Comment by ClaraDraper-NOAA** [comment]
@jiaruidong2017 is on AL for the next week. "test" if probably a better word than "flag".  The issue at the moment is that the workflow crashes ( I think at the stage where the obs are fetched) if the specified snow depth file does not exist, so we need to change that tool to allow for missing obs files. 

FYI: This came to light as @jswhit has been trying to cycle the workflow with the new snow DA turned on. He's hit some more issues since this one, including one that I think is a fortran bug, so we'll eventually have a collection of minor changes to make ( so could roll then all into a single PR).

**Comment by CoryMartin-NOAA** [comment]
@aerorahul this is one such application I think for the optional copy in FileHandler, but that may not exactly cover all the issues that this flag/test would solve

**Comment by jiaruidong2017** [comment]
Thanks @ClaraDraper-NOAA @CoryMartin-NOAA for the explanations. 

@aerorahul In the `super().initialize()` of `analysis.py`, a JEDI config file is first created from the predefined obs sources, then the obs files were copied to the running directory based on the pre-created JEDI config. If the observation file is missing, the run will crash due to (1) the copy in FileHandler and (2) the JEDI run. If the JEDI can handle the missing obs, it will be the only issue with the copy in FileHandler as mentioned by @CoryMartin-NOAA

**Comment by aerorahul** [comment]
[wxflow](https://github.com/NOAA-EMc/wxflow) has been updated to allow copying of files that may be optional.
This can be achieved by replacing `copy` with `copy_opt`.  If the file is not present, `FileHandler` will report a warning, but continue.
Please let me know if this is adequate for this issue or some more development is required/desired.

**Comment by jiaruidong2017** [comment]
Thanks @aerorahul for your updates. I close this issue for now, and will test the copy_opt for the missing obs.
