### ISSUE TITLE
Wrong version number for prepobs in operational workflow

### ISSUE THREAD

**Issue by ADCollard** [NOAA-EMC/global-workflow#2837]
### What is wrong?

The current version of `prepobs` in operations is 1.1.0.   In https://github.com/NOAA-EMC/global-workflow/blob/gfs.v16.3.16/versions/wcoss2.ver it is still 1.0.1.

### What should have happened?

Need correct version number

### What machines are impacted?

All or N/A

### Steps to reproduce

Operational prepbufr cannot be reproduced by the prep step in global-workflow

### Additional information

Asking @ilianagenkova to confirm this is correct.

**Comment by KateFriedman-NOAA** [comment]
@ADCollard are you talking about this in `versions/wcoss2.ver`?
```
export prepobs_run_ver=1.0.1
```

**Comment by KateFriedman-NOAA** [comment]
I think I see what @ADCollard is referencing, the `obsproc_gdas[gfs]_atmos_dump` jobs in ops are using the newer `prepobs/v1.1.0` package (via the module):
```
kate.friedman@clogin09:/lfs/h1/ops/prod/packages/gfs.v16.3.16> grep prepobs /lfs/h1/ops/prod/output/20240815/obsproc_gdas_atmos_dump_00.o175652603
+++ 1 + export prepobs_ver=1.1.0
+++ 1 + prepobs_ver=1.1.0
prepobs_ver=1.1.0
```

The GFS doesn't reference `prepobs` directly. The prepobs, especially now that it's a module, is effectively an upstream of the GFS upstream obsproc dependency. That version setting `prepobs_run_ver` in `versions/wcoss2.ver` is only used outside of ops during developer runs. The prepobs version is not set or referenced within the GFS otherwise.

This seems to have slipped through a crack. My guess is our `prepobs_run_ver` variable should have been updated to `1.1.0` when the [GFS went to `obsproc.v1.2` for `GFSv16.3.15` in late May](https://github.com/NOAA-EMC/global-workflow/releases/tag/gfs.v16.3.15).

@ADCollard Can you confirm that the prepbufr file is reproduced when you run with `prepobs_run_ver=1.1.0` in `versions/wcoss2.ver`?

**Comment by ilianagenkova** [comment]
Prepobs has been v1.1.0 since 22 May 2024. Before that it was 1.0.1Version v1.1.0 is needed for the uprair dumps obs to get into the prepbufr file ( they are ‘hiding’ into ADPUPA section of the prepbufr file) On Aug 15, 2024, at 9:42 PM, Kate Friedman ***@***.***> wrote:﻿
I think I see what @ADCollard is referencing, the obsproc_gdas[gfs]_atmos_dump jobs in ops are using the newer prepobs/v1.1.0 package (via the module):
***@***.***:/lfs/h1/ops/prod/packages/gfs.v16.3.16> grep prepobs /lfs/h1/ops/prod/output/20240815/obsproc_gdas_atmos_dump_00.o175652603
+++ 1 + export prepobs_ver=1.1.0
+++ 1 + prepobs_ver=1.1.0
prepobs_ver=1.1.0

The GFS doesn't reference prepobs directly. The prepobs, especially now that it's a module, is effectively an upstream of the GFS upstream obsproc dependency. That version setting prepobs_run_ver in versions/wcoss2.ver is only used outside of ops during developer runs. The prepobs version is not set or referenced within the GFS otherwise.
This seems to have slipped through a crack. My guess is our prepobs_run_ver variable should have been updated to 1.1.0 when the GFS went to obsproc.v1.2 for GFSv16.3.15 in late May.
@ADCollard Can you confirm that the prepbufr file is reproduced when you run with prepobs_run_ver=1.1.0 in versions/wcoss2.ver?

**Comment by KateFriedman-NOAA** [comment]
> Prepobs has been v1.1.0 since 22 May 2024. Before that it was 1.0.1Version v1.1.0 is needed for the uprair dumps obs to get into the prepbufr file ( they are ‘hiding’ into ADPUPA section of the prepbufr file)

Thanks for confirming @ilianagenkova ! I'll work to update the prepobs version in our v16 branch for developer use and also update our `develop` branch to use it for v17 testing.

**Comment by ADCollard** [comment]
@XuanliLi-NOAA ran a test case with prepobs v1.1.0 and was able to reproduce operations, confirming that this is the issue.

**Comment by ADCollard** [comment]
> > Prepobs has been v1.1.0 since 22 May 2024. Before that it was 1.0.1Version v1.1.0 is needed for the uprair dumps obs to get into the prepbufr file ( they are ‘hiding’ into ADPUPA section of the prepbufr file)
> 
> Thanks for confirming @ilianagenkova ! I'll work to update the prepobs version in our v16 branch for developer use and also update our `develop` branch to use it for v17 testing.

Thanks @KateFriedman-NOAA and @ilianagenkova !

**Comment by KateFriedman-NOAA** [comment]
> @XuanliLi-NOAA ran a test case with prepobs v1.1.0 and was able to reproduce operations, confirming that this is the issue.

Excellent, thanks for confirming @XuanliLi-NOAA and @ADCollard !

**Comment by KateFriedman-NOAA** [comment]
Released the updated `dev/gfs.v16` branch as `GFSv16.3.16.1`: https://github.com/NOAA-EMC/global-workflow/releases/tag/gfs.v16.3.16.1
