### ISSUE TITLE
Create regression test for modularized exglobal fcst script solution

### ISSUE THREAD

**Issue by lgannoaa** [NOAA-EMC/global-workflow#33]
The modularized exglobal fcst script is targeted for multiple supporting usage. How can we be sure adding new capability or bug fix will not break the existing functionality and still be able to generate identical result? Hence, the need to create a regression test for quality control.

The regression test should do the following to certify any change before commit/merge back to main repository by code manager:
1. Run jobs using canned data on each certified target to ensure the new package reproduce the forecast result.
2. Test configuration scope should include cold/warm/rerun.
3. Test results should be uploaded to HPSS for record keeping.
4. Previously certified executable and canned data including initial condition that will be used to run the regression test should be in version control environment. 
5. Each main repository merge should have documentation on how regression test was preformed.
6. Regression test should support all platform which exglobal forecast script supported.

**Comment by KateFriedman-NOAA** [comment]
@lgannoaa @JianKuang-NOAA Is this still happening? If not, please close issue, thanks!

**Comment by lgannoaa** [comment]
@KateFriedman-NOAA I am not involved on this task. Thanks

**Comment by KateFriedman-NOAA** [comment]
@JianKuang-UMD Is this still an ongoing task? If not, this should be closed. Thanks!

**Comment by jkuang-exploro** [comment]
I think this job needs some high-level architecting to start with. For example: What's the relationship between this proposed regression test and the tests within ufs repo. Do we really need to run the experiment or just provide the namelists(the primary purpose of the script). 

I feel that we don't really need to submit the job ticket to perform a script-level regression test because once the namelists are there, the goal of the script is achieved. And here's what I think it should happen: Create a separate fcst_regtest.sh script at the same level of fcst.sh but with additional environment variable telling the script to not actually run the experiment (activate sandbox).
