### ISSUE TITLE
Ice dimensions should be set based on resolution

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#435]
Right now NX_GLB and NY_GLB are hard-coded in the config file. They should be set based on the ice model resolution.

**Comment by JessicaMeixner-NOAA** [comment]
These should also be set based on how many ice processors there are, see https://github.com/ufs-community/ufs-weather-model/blob/develop/tests/edit_inputs.sh#L7-L9

**Comment by lgannoaa** [comment]
@JessicaMeixner-NOAA @WalterKolczynski-NOAA, is the Ice dimensions support only one resolution? NX_GLB="1440" and NY_GLB="1080" in config.ice indicate there many be additional application logic needed for ensure it match the resolution configured in running workflow.

**Comment by JessicaMeixner-NOAA** [comment]
NX_GLB and NY_GLB should be set based on ice resolution: 

1 degree: 
NX_GLB=360
NY_GLB=320

1/2 deg: 
NX_GLB=720
NY_GLB=576

1/4 deg: 
NX_GLB=1440
NY_GLB=1080

The comment about the number of ice processors is actually already taken care of here: https://github.com/NOAA-EMC/global-workflow/blob/develop/ush/parsing_namelists_CICE.sh#L177-L180 

Note that NX_GLB and NY_GLB are also used by MOM6, and we do correctly recompute these values here: https://github.com/NOAA-EMC/global-workflow/blob/develop/ush/parsing_namelists_MOM6.sh#L25-L54 based on resolution which is maybe why if anyone has run with a non 1/4 degree resolution it has been fine.

**Comment by lgannoaa** [comment]
@JessicaMeixner-NOAA two clarifications:
1. Looks like the domain_nml session control the runtime compute resource assignment. But it is not impact the job resource assigned which is configured in config.resource. Do we need to modify config.resource for this job to use system resource based on resolution?
2. parsing_namelists_MOM6.sh used default OCNRES is 025. However, config.base has no default reference value on config.base. That indicated user need to specified this value in config.base after setup of the expdir. Or unaware of this 025 default is being used. Maybe it can be modified by evaluate resolution from config.base?

**Comment by JessicaMeixner-NOAA** [comment]
@lgannoaa  It would make sense if different resources are used for different resolutions of the ocean/ice model.  

I believe the ocean/ice resolution is determined here: https://github.com/NOAA-EMC/global-workflow/blob/develop/parm/config/config.base.emc.dyn#L206-L214 based on the ATM model resolution right now.

**Comment by JessicaMeixner-NOAA** [comment]
@lgannoaa follow up: we already have variable ocean/ice resources based on resolution: https://github.com/NOAA-EMC/global-workflow/blob/develop/parm/config/config.resources#L238-L256

**Comment by lgannoaa** [comment]
> @lgannoaa follow up: we already have variable ocean/ice resources based on resolution: https://github.com/NOAA-EMC/global-workflow/blob/develop/parm/config/config.resources#L238-L256

Looks like config.resources set both gfs and gdas with the same NTASKS_TOT to compute job resource/jobs card. Is this desired behavior?

**Comment by lgannoaa** [comment]
@JessicaMeixner-NOAA a search on job script, it does not look like file config.ice has been sourced. May I know how is this config file been used?

**Comment by JessicaMeixner-NOAA** [comment]
@lgannoaa I don't remember creating this file, so as your grep shows, perhaps it's not being used at all.  @WalterKolczynski-NOAA made this issue, maybe he remembers more about it?

**Comment by lgannoaa** [comment]
> > @lgannoaa follow up: we already have variable ocean/ice resources based on resolution: https://github.com/NOAA-EMC/global-workflow/blob/develop/parm/config/config.resources#L238-L256
> 
> Looks like config.resources set both gfs and gdas with the same NTASKS_TOT to compute job resource/jobs card. Is this desired behavior?

@JessicaMeixner-NOAA do you have an answer for this question?

**Comment by WalterKolczynski-NOAA** [comment]
> @JessicaMeixner-NOAA a search on job script, it does not look like file config.ice has been sourced. May I know how is this config file been used?

config.ice is sourced by config.fcst when DO_ICE is "YES"

**Comment by JessicaMeixner-NOAA** [comment]
@lgannoaa we are currently only running coupled in with gfs right now, I think this functionality is fine.  I think the issue that is being raised in this issue is simply that 
config.ice should be something like: 

```
case $ICERES in 
025) NX_GLB=1440  NY_GLB=1080 ;;
050)  
100) 
*) "fatal" 
esac 
```
I think this conversation is getting way out of the scope of the original intent of this issue.

**Comment by WalterKolczynski-NOAA** [comment]
> @WalterKolczynski-NOAA, looks like config.fcst has statement export cplice=".false." and changed to export cplice=".true." later in the script without the code remark as you requested in PR #740 . This indicated there is a double standard on your code review. Would you please let us know why?

- In this instance, cplice is being changed directly afterwards in the same code block, not 70 lines later after a bunch of different code
- There *is* a note even closer than that that cpl changes based on app
- No one is trying to treat you differently. Reviews aren't always going to pick up on the same things because (a) we're human, (b) the focus of the changes and the pressure to merge isn't always the same, and (c) some of the code was written months or even years ago and not been brought up to standard. The goal isn't to make you do more work, it is to make the code better. If you think you are being treated unfairly, please bring it up privately, CCing whoever you feel you need to, and not on an issue (and certainly not an unrelated issue like this one).

**Comment by lgannoaa** [comment]
The use of the following in config.fcst does not follow the standard of the way global workflow source configuration file. 

for component in WAVE OCN ICE AERO; do
  control="DO_${component}"
  if [[ $(eval echo \$$control) == "YES" ]]; then
    . $EXPDIR/config.$(echo "$component" | awk '{ print tolower($1) }')
  fi
done

Especially, using awk '{ print tolower($1) }' to convert upper case to lower case in configuration file name is going to make search more difficult in addition to the fact that rest of the workflow using lower case to source config file. File config.fcst unconditionally source WAVE OCN ICE AERO config file without evaluate if the function has been turned on or not. Maybe there is a need to create a different GitHub issue to address this problem.
It is also determined that the solution requested in this issue to modify config.ice is still pending. Because config.resources in global workflow develop has:
Line 329
( Except for 025, these are guesses for now)
100) export OCNPETS=20 ;;
050) export OCNPETS=60 ;;
025) export OCNPETS=220 ;;
Line 253
( Except for 025, these are guesses for now)
100) export ICEPETS=10 ;;
050) export ICEPETS=30 ;;
025) export ICEPETS=80 ;;
This means the job card resource for case 050 and 100 are not tested. 
Looks like the resource assignment purposed here should pending on code manager confirm the job resource and fully tested to implement the following change into config.ice file.
1 degree:
NX_GLB=360
NY_GLB=320

1/2 deg:
NX_GLB=720
NY_GLB=576

**Comment by aerorahul** [comment]
I think this was addressed when `config.ufs` was introduced where `NX_GLB` and `NY_GLB` are defined based on the ocean resolution.
