### ISSUE TITLE
MET+ job dependencies

### ISSUE THREAD

**Issue by jkuang-exploro** [NOAA-EMC/global-workflow#437]
The MET+ job in the first full cycle wont run, because it depends on gfs archive job of the previous cycle which doesn't exist in the first half cycle. Job dependency and/or job scripts need to be updated to get rid of this problem.

**Comment by jkuang-exploro** [comment]
@malloryprow May I know that at which cycles will metp jobs run? Is the first full cycle the only one we need to worry about? In other words, do these jobs run at every full cycle from the second full cycle(third cycle) and beyond?

**Comment by malloryprow** [comment]
@JianKuang-UMD They run every GFS cycle.

**Comment by jkuang-exploro** [comment]
After reviewing the metp+ job scripts, I feel the most feasible solution is to remove the dependency of gfsarch from previous cycle. In fact this issue only exist in the first full cycle since gfsarch doesn't exist for the first half cycle.

**Comment by jkuang-exploro** [comment]
@malloryprow @WalterKolczynski-NOAA Let's move our conversation here since I'm about to close that PR and re-initiate it from a new branch.

**Comment by jkuang-exploro** [comment]
@malloryprow I agree with making metp dependency to the gfsarch job of the current cycle, if that's the intention.

**Comment by malloryprow** [comment]
@JianKuang-UMD Yes, I think that would be good.

**Comment by jkuang-exploro** [comment]
@malloryprow I was told that running jobs after archive is not a viable plan. So instead we need to identify all specific data files that metp needs from ARCDIR. And making them available for metp either through a step in verification job or a new job. Would you please email me those data files?

**Comment by jkuang-exploro** [comment]
I will write up a simple job moving those data into ARCDIR before metp.

**Comment by malloryprow** [comment]
@aerorahul @KateFriedman-NOAA @JianKuang-UMD I see that the gfsarch has a task dependency on gfsvrfy. I'm guessing this is done so gfsarch only runs after gfsvrfy is complete, not sure if this is because more related to a data dependency or just related to the flow or progression of the jobs. Should a similar dependency exists for gfsarch for gfsmetp?

**Comment by aerorahul** [comment]
@malloryprow 
The `gfsarch` depends on `gfsvrfy` because it probably archives the data produced in `gfsvrfy` and more importantly `gfsvrfy` depends on the data in `ROTDIR`, which `gfsarch` possibly removes as part of the cleaning (We know that should be its own task).  If `gfsvrfy` does not depend on data in `ROTDIR`, then that dependency should be corrected.

Does `metp` produce data that needs to be archived or cleaned after it is run?  If it does, then `gfsarch` should depend on `metp`.

**Comment by malloryprow** [comment]
@aerorahul Got it, since the gfsmetp will be need data from the ROTDIR for the current cycle it sounds like the dependency should be added? gfsmetp doesn't require any cleaning or archiving done by gfsach.
