### ISSUE TITLE
[Products] gempak related scripts/jobs/tools

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/global-workflow#531]
This [gempak](https://github.com/NOAA-EMC/global-workflow/tree/develop/gempak) directory in the global-workflow repository needs a repository for its own development and maintenance.
Who is the owner/developer/maintainer of these gempak related scripts/jobs/tools?

**Comment by WalterKolczynski-NOAA** [comment]
Is this still something we want to do? We're moving scripts from other repos _into_ workflow, and there is no source code here. I think it would be better to move these to appropriate places in the larger workflow instead of isolated in their own directory. Contents of both `dictionaries` and `fix` would be appropriate in a `parm/gempak`. `ush` would move to the main `ush`, of course.

**Comment by aerorahul** [comment]
This is NCO managed directory.
Unlikely this will move anywhere.
