### ISSUE TITLE
Split clean-up activities off from archive job

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#583]
Right now the clean-up of older cycles is handled within the archive script. This should be split out into its own script and job.

**Comment by lgannoaa** [comment]
The current clean-up activities is located within archive job. The reason for this design is because archive job run at the end of a cycle. Which has job dependency on previous job successfully completed. This job proceed with necessary archive task before the clean up stage. The clean up stage process predefined application logic to evaluate what files/directories to be removed. The clean-up activities work its best to function within the archive job. May I know which management support this modification activity?

**Comment by lgannoaa** [comment]
@WalterKolczynski-NOAA , would you please take a look at my comment above and reply? Thanks

**Comment by WalterKolczynski-NOAA** [comment]
Archival and clean-up are two completely separate functions, so they should be two separate jobs (and scripts, obviously). There's no reason a user should have to run an 'archive' job if they do not wish to do any archival (or vice versa). We're trying to move to shorter, more maintainable jobs (or, where that isn't possible, at least scripts).

**Comment by lgannoaa** [comment]
We need to have design and requirement document before development. Please let me know when it is available, so I can take this issue.
