### ISSUE TITLE
Move namelist building outside of forecast job

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#584]
Right now we are creating most of our namelists and other setting files for the forecast during the forecast job. Since these are generally serial operations, this is wasting thousands of cores while waiting for the actual forecast to kick off. Also, these don't need to wait for init data to be in place first, so they could be created earlier, giving a small timing advantage.

Copying/linking will still need to be done as part of the forecast job (since the run directory doesn't exist until then), but other activities can be moved into a separate job.

**Comment by WalterKolczynski-NOAA** [comment]
I can be convinced these operations are so fast that it isn't work the effort.

**Comment by JessicaMeixner-NOAA** [comment]
What about namelist updates that are based on a re-run?  Would you have to then re-run the prep job?

**Comment by yangfanglin** [comment]
Making the job script flexible for running different types of forecasts at different resolutions is important for model development, even though it might be  less desire for operation where settings are fixed.  Yes, "these operations are so fast..."

**Comment by WalterKolczynski-NOAA** [comment]
> What about namelist updates that are based on a re-run? Would you have to then re-run the prep job?

This is a good point

**Comment by WalterKolczynski-NOAA** [comment]
> Making the job script flexible for running different types of forecasts at different resolutions is important for model development, even though it might be  less desire for operation where settings are fixed.  Yes, "these operations are so fast..."

I don't see any reason moving these to their own job run just before the forecast would preclude any of those things.

**Comment by arunchawla-NOAA** [comment]
we assign a number of processors to the forecast step, if we have an error at the namelist creation / checking level then we are potentially wasting resources. I was thinking that namelists would be created at the experiment set up level, but that would not work for changes that have to be done for reruns

**Comment by aerorahul** [comment]
Even if namelists are created at experiment setup level, there are some parameters in namelists e.g. stochastic physics that are (random) seeds based on cycle and ensemble member.  This is perhaps the only example I can find that has runtime information.  Other runtime information is related to cycle date, which I think occurs in several places in the GFS.

The setup can take us a lot farther, configuration can occur based on the set up at runtime and could be much faster/quicker.  The only advantage with creating bulk of the namelist at setup time allows the developer/user to take a peek at what it will look like for the rest of the experiment, rather than in a fleeting moment at runtime. 
This capability, IMO is quite desirable.  

This matters not just for the forecast job, but also for other jobs e.g. analysis, enkf, etc.

**Comment by WalterKolczynski-NOAA** [comment]
I had envisioned a separate fcst prep job run before the forecast, but I'm not against something created at setup time. As Rahul points out, that method has its advantages. We should be able to set it up so that just a few settings like date and whatever is needed for restarts are templated and we just fill in those few key parameters at runtime.

**Comment by WalterKolczynski-NOAA** [comment]
Wil likely handled as part of #1347
