### ISSUE TITLE
Separate threading options for gdasfcst and gfsfcst

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/global-workflow#610]
**Expected behavior**

When `nth_fv3` is different from `nth_fv3_gfs` in config.fv3, config.resources should reference those options when calculating forecast GFS and GDAS forecasts.

**Current behavior**

Only the `nth_fv3` variable is referenced on [line 211](https://github.com/NOAA-EMC/global-workflow/blob/d3028b9d8268028226f9c27800fcd6655e9e4bb8/parm/config/config.resources#L211), resulting in the same threading option for both GDAS and GFS forecasts.

**Machines affected**

S4, which will use different threading options for GDAS and GFS forecasts.

**To Reproduce**

Manually set `nth_fv3` to 2, `nth_fv3_gfs` to 1, then run `setup_expt.py` and `setup_workflow.py`.  The resulting .xml will use 2 threads for both the GFS and GDAS forecasts.

**Context**

This should only immediately affect users on S4.

**Detailed Description**

Moving the `nth_fcst` assignment into the `if` block [starting on line 192 of config.resources](https://github.com/NOAA-EMC/global-workflow/blob/d3028b9d8268028226f9c27800fcd6655e9e4bb8/parm/config/config.resources#L192) and adding an `else` will allow users to specify different threading options.

**Additional Information**

**Possible Implementation**

I will add the suggested fix momentarily.

**Comment by KateFriedman-NOAA** [comment]
@DavidHuber-NOAA Thanks for reporting this bug! We had a similar bug on the `operations` branch side that I fixed with a similar fix during the GFSv16.0.7 upgrade. See the line 10 addition in this commit: https://github.com/NOAA-EMC/global-workflow/commit/3786256240e76982c54a5be6d8a7277530d9dd47

During the WCOSS2 port, where we needed similar differentiation between the gdas/gfs suites, I also adjusted the setup scripts to support `_gfs` versions of resource values (threads, tasks, ppn, and memory). See the `get_resources` function in the WCOSS2 port branch copy of workflow_utils.py: https://github.com/NOAA-EMC/global-workflow/blob/feature/ops-wcoss2/ush/rocoto/workflow_utils.py#L279:L309

We may need to consider similar updates too in the setup scripts, in addition to possible config adjustments (I haven't looked at workflow_utils.py for this yet). Your [PR change](https://github.com/NOAA-EMC/global-workflow/pull/611/files) looks good to me at first glance, will let others chime in.
