### ISSUE TITLE
Archive lists should not be written to COM

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#760]
**Description**
The archive job is currently writing the lists of files to archive to COM. These are temporary files that should not be written to COM at all; they should use $DATA and be deleted after the archive action completes.

**Requirements**
An archive job that uses $DATA instead of COM, and deletes $DATA after successful completion.

**Dependencies**
None

**Comment by XianwuXue-NOAA** [comment]
When generate the list, a function to check the file exists or not should be added to the archive script. Because when I ATM with aerosol, the archive always failed and I found some the *.anl files do not exist, which caused the htar failed. Do you have plan to improve it? If not, we may create another issue to solve this.

**Comment by WalterKolczynski-NOAA** [comment]
> When generate the list, a function to check the file exists or not should be added to the archive script. Because when I ATM with aerosol, the archive always failed and I found some the *.anl files do not exist, which caused the htar failed. Do you have plan to improve it? If not, we may create another issue to solve this.

That's unrelated to this issue.
